apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: petstore-api
        image: ghcr.io/turtlejrp/devops-java-example:d14eee724f3eeb4f1093a660bb1fe8da712b6fe9
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
